### ISSUE TITLE
Latest commit does not successfully start

### ISSUE THREAD

**Issue by nrgbistro** [rmountjoy92/DashMachine#26]
So far I have tried completely removing the config folder (to replicate a fresh install). Here is the error produced on startup:

```

[2020-03-08 20:07:24 +0000] [1] [INFO] Starting gunicorn 20.0.4,
[2020-03-08 20:07:24 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1),
[2020-03-08 20:07:24 +0000] [1] [INFO] Using worker: sync,
[2020-03-08 20:07:24 +0000] [7] [INFO] Booting worker with pid: 7,
/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:834: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.,
  warnings.warn(FSADeprecationWarning(,
[2020-03-08 20:07:24 +0000] [7] [ERROR] Exception in worker process,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker,
    worker.init_process(),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process,
    self.load_wsgi(),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi,
    self.wsgi = self.app.wsgi(),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi,
    self.callable = self.load(),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load,
    return self.load_wsgiapp(),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp,
    return util.import_app(self.app_uri),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app,
    mod = importlib.import_module(module),
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/dashmachine/wsgi.py", line 3, in <module>,
    from dashmachine import app,
  File "/dashmachine/dashmachine/__init__.py", line 29, in <module>,
    from dashmachine.main.routes import main,
  File "/dashmachine/dashmachine/main/routes.py", line 10, in <module>,
    from dashmachine.main.utils import (,
  File "/dashmachine/dashmachine/main/utils.py", line 4, in <module>,
    from PIL import Image, ImageOps,
ModuleNotFoundError: No module named 'PIL',
[2020-03-08 20:07:24 +0000] [7] [INFO] Worker exiting (pid: 7),
[2020-03-08 20:07:24 +0000] [1] [INFO] Shutting down: Master,
[2020-03-08 20:07:24 +0000] [1] [INFO] Reason: Worker failed to boot.,

```

**Comment by Starker3** [comment]
Same issue, using the docker build here

**Comment by rmountjoy92** [comment]
please pull rmountjoy/dashmachine:latest it should be fixed.

**Comment by auanasgheps** [comment]
I you have updated the image, it has not been published to Docker Hub (yet).
[Here](https://hub.docker.com/r/rmountjoy/dashmachine/builds) shows "5 hours ago". Indeed if I try to recreate the container it's still broken with the same error.

**Comment by di-dc** [comment]
I had to do this (via the readme), and then everything was fine:

> Note: if you update DashMachine and it fails to start, it's possible something is messed up with your database file. Backup your files in the user_data folder, delete the contents and restart DashMachine. This will reset your user table, so log in with the default user/pass.

I think it's because of the new option for changing the title.

**Comment by nrgbistro** [comment]
I had done that earlier and it didn't seem to work. I tried removing the config folder again and this time I deleted the old image in Portainer and it seems to work just fine now. Thanks!
