### ISSUE TITLE
Docker updates are breaking database

### ISSUE THREAD

**Issue by Nixellion** [rmountjoy92/DashMachine#41]
Some people on reddit are complaining that docker container updates are breaking database. Worth checking database migration code.

Logs

```
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table settings has no column named home_view_mode
[SQL: INSERT INTO settings (theme, accent, background, roles, home_access_groups, settings_access_groups, home_view_mode, custom_app_title) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('dark', 'orange', '', 'admin,user,public_user', 'admin_only', 'admin_only', 'grid', 'DashMachine')]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2020-03-18 15:20:41 +0000] [7] [INFO] Worker exiting (pid: 7)
[2020-03-18 15:20:41 +0000] [1] [INFO] Shutting down: Master
[2020-03-18 15:20:41 +0000] [1] [INFO] Reason: Worker failed to boot.
[2020-03-18 15:20:49 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-03-18 15:20:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-03-18 15:20:49 +0000] [1] [INFO] Using worker: sync
[2020-03-18 15:20:49 +0000] [7] [INFO] Booting worker with pid: 7
/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:834: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(
[2020-03-18 15:20:50 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table settings has no column named home_view_mode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/dashmachine/wsgi.py", line 6, in <module>
    dashmachine_init()
  File "/dashmachine/dashmachine/main/utils.py", line 55, in dashmachine_init
    read_config()
  File "/dashmachine/dashmachine/main/read_config.py", line 71, in read_config
    db.session.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table settings has no column named home_view_mode
[SQL: INSERT INTO settings (theme, accent, background, roles, home_access_groups, settings_access_groups, home_view_mode, custom_app_title) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('dark', 'orange', '', 'admin,user,public_user', 'admin_only', 'admin_only', 'grid', 'DashMachine')]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2020-03-18 15:20:50 +0000] [7] [INFO] Worker exiting (pid: 7)
[2020-03-18 15:20:50 +0000] [1] [INFO] Shutting down: Master
[2020-03-18 15:20:50 +0000] [1] [INFO] Reason: Worker failed to boot
```

**Comment by rmountjoy92** [comment]
Yeah, I need to figure out what's going on with alembic, it's strange, sometimes it works sometimes it throws those errors.

**Comment by rmountjoy92** [comment]
this should be fixed in 259068e6188d1423c03ec2a69a91979ae3113e90, moving forward it shouldn't have issues upgrading, though before I push it to master, I'm going to try to figure out how I can do it without people deleting their databases one more time. If not people will have to delete it one more time.

**Comment by Starker3** [comment]
It might be worth using tags when pushing updates to docker hub so people can roll back to a specific version if they run into an issue while waiting for it to be fixed

**Comment by nrgbistro** [comment]
I would assume that this is related. My homepage has 4 copies of the same tag (I have a tag for media and the same section is repeated multiple times despite no change in configuration.

**Comment by volcan96** [comment]
Not sure I'm doing this right, but I'm still seeing this issue on the development branch.

On my RPI4 I did the following

```
$ git clone http://github.com/rmountjoy92/DashMachine.git
$ git branch -a
$ git pull origin develop
```
which then gives this warning:
```

warning: redirecting to https://github.com/rmountjoy92/DashMachine.git/
From http://github.com/rmountjoy92/DashMachine
 * branch            develop    -> FETCH_HEAD
Already up to date.
```
Then I change Dockerfile to the following:
```
FROM arm32v7/python:3.8-slim

RUN apt-get update -q \
  && apt-get install apt-utils inetutils-ping python python-pip python-dev libffi-dev libjpeg-dev zlib1g-dev -y \
  && rm -rf /var/lib/apt/lists/*

COPY [ "requirements.txt", "/dashmachine/" ]

WORKDIR /dashmachine

RUN pip install --no-cache-dir --progress-bar on -r requirements.txt

COPY [ ".", "/dashmachine/" ]

ENV PRODUCTION=true
EXPOSE 5000
VOLUME /dashmachine/dashmachine/user_data
CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app" ]
```

and run the following and wait for 5 mins or so:
```
sudo docker build -t <myimagenamehere> .
```
I get a bunch of build code and at the end get the following indicating a successful build:
```
Successfully built 01c258135803
Successfully tagged volcan96/dashmachine-rpi:latest
```
I have a docker-compose.yml file with the following (which worked on previous DashMachine versions):

```
version: '2'

services:
    dashmachine:
      image:<myimagenamehere>
      restart: unless-stopped
      volumes:
      - /home/pi/dashmachine/_data:/dashmachine/dashmachine/user_data
      environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
```
so then I run:
```
sudo docker-compose up
```
and the docker container starts but then exits with:
```
Attaching to dashmachine_dashmachine_1
dashmachine_1  | [2020-03-19 16:00:43 -0700] [1] [INFO] Starting gunicorn 20.0.4
dashmachine_1  | [2020-03-19 16:00:43 -0700] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
dashmachine_1  | [2020-03-19 16:00:43 -0700] [1] [INFO] Using worker: sync
dashmachine_1  | [2020-03-19 16:00:43 -0700] [8] [INFO] Booting worker with pid: 8
dashmachine_1  | [2020-03-19 16:00:44 -0700] [8] [ERROR] Exception in worker process
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
dashmachine_1  |     self.dialect.do_execute(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
dashmachine_1  |     cursor.execute(statement, parameters)
dashmachine_1  | sqlite3.OperationalError: table settings has no column named custom_app_title
dashmachine_1  | 
dashmachine_1  | The above exception was the direct cause of the following exception:
dashmachine_1  | 
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
dashmachine_1  |     worker.init_process()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
dashmachine_1  |     self.load_wsgi()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
dashmachine_1  |     self.wsgi = self.app.wsgi()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
dashmachine_1  |     self.callable = self.load()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
dashmachine_1  |     return self.load_wsgiapp()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
dashmachine_1  |     return util.import_app(self.app_uri)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
dashmachine_1  |     mod = importlib.import_module(module)
dashmachine_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
dashmachine_1  |     return _bootstrap._gcd_import(name[level:], package, level)
dashmachine_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
dashmachine_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
dashmachine_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
dashmachine_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
dashmachine_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
dashmachine_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
dashmachine_1  |   File "/dashmachine/wsgi.py", line 6, in <module>
dashmachine_1  |     dashmachine_init()
dashmachine_1  |   File "/dashmachine/dashmachine/main/utils.py", line 55, in dashmachine_init
dashmachine_1  |     read_config()
dashmachine_1  |   File "/dashmachine/dashmachine/main/read_config.py", line 71, in read_config
dashmachine_1  |     db.session.commit()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
dashmachine_1  |     return getattr(self.registry(), name)(*args, **kwargs)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
dashmachine_1  |     self.transaction.commit()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 503, in commit
dashmachine_1  |     self._prepare_impl()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
dashmachine_1  |     self.session.flush()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
dashmachine_1  |     self._flush(objects)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
dashmachine_1  |     transaction.rollback(_capture_exception=True)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
dashmachine_1  |     compat.raise_(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
dashmachine_1  |     raise exception
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
dashmachine_1  |     flush_context.execute()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
dashmachine_1  |     rec.execute(self)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
dashmachine_1  |     persistence.save_obj(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
dashmachine_1  |     _emit_insert_statements(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
dashmachine_1  |     result = cached_connections[connection].execute(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
dashmachine_1  |     return meth(self, multiparams, params)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
dashmachine_1  |     return connection._execute_clauseelement(self, multiparams, params)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
dashmachine_1  |     ret = self._execute_context(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
dashmachine_1  |     self._handle_dbapi_exception(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
dashmachine_1  |     util.raise_(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
dashmachine_1  |     raise exception
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
dashmachine_1  |     self.dialect.do_execute(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
dashmachine_1  |     cursor.execute(statement, parameters)
dashmachine_1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table settings has no column named custom_app_title
dashmachine_1  | [SQL: INSERT INTO settings (theme, accent, background, roles, home_access_groups, settings_access_groups, home_view_mode, custom_app_title) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
dashmachine_1  | [parameters: ('light', 'deepOrange', 'static/images/backgrounds/blurry_rainy_day.jpg', 'admin,user,public_user', 'admin_only', 'admin_only', 'grid', 'DashMachine')]
dashmachine_1  | (Background on this error at: http://sqlalche.me/e/e3q8)
dashmachine_1  | [2020-03-19 16:00:44 -0700] [8] [INFO] Worker exiting (pid: 8)
dashmachine_1  | [2020-03-19 16:00:44 -0700] [1] [INFO] Shutting down: Master
dashmachine_1  | [2020-03-19 16:00:44 -0700] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by Starker3** [comment]
I'm still getting an 
"Internal Server Error" even with the latest docker image, I have tried removing the db file and starting the docker container again but that didn't work

**Comment by volcan96** [comment]
Another update; while I was able to get the app running in docker I got the same behavior as @Starker3 

I can upload images...but adding ANY new app to the ini breaks the app. Output below:

```
pi@rpi4:~/DashMachine $ sudo docker-compose up
Starting dashmachine_dashmachine_1 ... done
Attaching to dashmachine_dashmachine_1
dashmachine_1  | [2020-03-19 21:56:26 -0700] [1] [INFO] Starting gunicorn 20.0.4
dashmachine_1  | [2020-03-19 21:56:26 -0700] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
dashmachine_1  | [2020-03-19 21:56:26 -0700] [1] [INFO] Using worker: sync
dashmachine_1  | [2020-03-19 21:56:26 -0700] [7] [INFO] Booting worker with pid: 7
dashmachine_1  | [2020-03-19 21:57:23,584] ERROR in app: Exception on /settings [GET]
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
dashmachine_1  |     response = self.full_dispatch_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
dashmachine_1  |     rv = self.handle_user_exception(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
dashmachine_1  |     return original_handler(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
dashmachine_1  |     reraise(exc_type, exc_value, tb)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
dashmachine_1  |     raise value
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
dashmachine_1  |     rv = self.dispatch_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
dashmachine_1  |     return self.view_functions[rule.endpoint](**req.view_args)
dashmachine_1  |   File "/dashmachine/dashmachine/settings_system/routes.py", line 39, in settings
dashmachine_1  |     files_html = load_files_html()
dashmachine_1  |   File "/dashmachine/dashmachine/settings_system/utils.py", line 16, in load_files_html
dashmachine_1  |     return render_template(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 136, in render_template
dashmachine_1  |     ctx.app.update_template_context(context)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 838, in update_template_context
dashmachine_1  |     context.update(func())
dashmachine_1  |   File "/dashmachine/dashmachine/sources.py", line 86, in context_processor
dashmachine_1  |     tags += app_db.tags.split(",")
dashmachine_1  | AttributeError: 'NoneType' object has no attribute 'split'
dashmachine_1  | [2020-03-19 21:57:23 -0700] [7] [ERROR] Error handling request /settings
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
dashmachine_1  |     response = self.full_dispatch_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
dashmachine_1  |     rv = self.handle_user_exception(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
dashmachine_1  |     return original_handler(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
dashmachine_1  |     reraise(exc_type, exc_value, tb)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
dashmachine_1  |     raise value
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
dashmachine_1  |     rv = self.dispatch_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
dashmachine_1  |     return self.view_functions[rule.endpoint](**req.view_args)
dashmachine_1  |   File "/dashmachine/dashmachine/settings_system/routes.py", line 39, in settings
dashmachine_1  |     files_html = load_files_html()
dashmachine_1  |   File "/dashmachine/dashmachine/settings_system/utils.py", line 16, in load_files_html
dashmachine_1  |     return render_template(
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 136, in render_template
dashmachine_1  |     ctx.app.update_template_context(context)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 838, in update_template_context
dashmachine_1  |     context.update(func())
dashmachine_1  |   File "/dashmachine/dashmachine/sources.py", line 86, in context_processor
dashmachine_1  |     tags += app_db.tags.split(",")
dashmachine_1  | AttributeError: 'NoneType' object has no attribute 'split'
dashmachine_1  | 
dashmachine_1  | During handling of the above exception, another exception occurred:
dashmachine_1  | 
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
dashmachine_1  |     self.handle_request(listener, req, client, addr)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
dashmachine_1  |     respiter = self.wsgi(environ, resp.start_response)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
dashmachine_1  |     return self.wsgi_app(environ, start_response)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
dashmachine_1  |     response = self.handle_exception(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
dashmachine_1  |     return original_handler(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1878, in handle_exception
dashmachine_1  |     server_error = handler(server_error)
dashmachine_1  |   File "/dashmachine/dashmachine/error_pages/routes.py", line 21, in error_500
dashmachine_1  |     return render_template("/error_pages/500.html"), 500
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 136, in render_template
dashmachine_1  |     ctx.app.update_template_context(context)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 838, in update_template_context
dashmachine_1  |     context.update(func())
dashmachine_1  |   File "/dashmachine/dashmachine/sources.py", line 86, in context_processor
dashmachine_1  |     tags += app_db.tags.split(",")
dashmachine_1  | AttributeError: 'NoneType' object has no attribute 'split'
dashmachine_1  | [2020-03-19 21:57:23,700] ERROR in app: Exception on /favicon.ico [GET]
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
dashmachine_1  |     response = self.full_dispatch_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
dashmachine_1  |     rv = self.handle_user_exception(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
dashmachine_1  |     return original_handler(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
dashmachine_1  |     reraise(exc_type, exc_value, tb)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
dashmachine_1  |     raise value
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1947, in full_dispatch_request
dashmachine_1  |     rv = self.preprocess_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2241, in preprocess_request
dashmachine_1  |     rv = func()
dashmachine_1  |   File "/dashmachine/dashmachine/main/routes.py", line 45, in check_valid_login
dashmachine_1  |     request.endpoint.startswith("static"),
dashmachine_1  | AttributeError: 'NoneType' object has no attribute 'startswith'
dashmachine_1  | [2020-03-19 21:57:23 -0700] [7] [ERROR] Error handling request /favicon.ico
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
dashmachine_1  |     response = self.full_dispatch_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
dashmachine_1  |     rv = self.handle_user_exception(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
dashmachine_1  |     return original_handler(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
dashmachine_1  |     reraise(exc_type, exc_value, tb)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
dashmachine_1  |     raise value
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1947, in full_dispatch_request
dashmachine_1  |     rv = self.preprocess_request()
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2241, in preprocess_request
dashmachine_1  |     rv = func()
dashmachine_1  |   File "/dashmachine/dashmachine/main/routes.py", line 45, in check_valid_login
dashmachine_1  |     request.endpoint.startswith("static"),
dashmachine_1  | AttributeError: 'NoneType' object has no attribute 'startswith'
dashmachine_1  | 
dashmachine_1  | During handling of the above exception, another exception occurred:
dashmachine_1  | 
dashmachine_1  | Traceback (most recent call last):
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
dashmachine_1  |     self.handle_request(listener, req, client, addr)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
dashmachine_1  |     respiter = self.wsgi(environ, resp.start_response)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
dashmachine_1  |     return self.wsgi_app(environ, start_response)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
dashmachine_1  |     response = self.handle_exception(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
dashmachine_1  |     return original_handler(e)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1878, in handle_exception
dashmachine_1  |     server_error = handler(server_error)
dashmachine_1  |   File "/dashmachine/dashmachine/error_pages/routes.py", line 21, in error_500
dashmachine_1  |     return render_template("/error_pages/500.html"), 500
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 136, in render_template
dashmachine_1  |     ctx.app.update_template_context(context)
dashmachine_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 838, in update_template_context
dashmachine_1  |     context.update(func())
dashmachine_1  |   File "/dashmachine/dashmachine/sources.py", line 86, in context_processor
dashmachine_1  |     tags += app_db.tags.split(",")
dashmachine_1  | AttributeError: 'NoneType' object has no attribute 'split'


```

**Comment by volcan96** [comment]
For anyone that wants to get DashMachine working, just go back to an earlier commit. I'm putting this for a reference. This assumes a python install but can be modified for docker.

first clone the repo.
```
$ git clone https://github.com/rmountjoy92/DashMachine.git
```

then go back to a commit
```
$ git reset --hard 8b82140    # this goes back to a Feb 23 commit
or 
$ git checkout 8b82140 # note that I didn't test this
```
proceed with the build steps

**Comment by fosspill** [comment]
Any idea how one would do this for docker? The current version in master is completely broken, so rolling back would be lovely.

**Comment by rmountjoy92** [comment]
Hello all, 

A fix for this in incoming shortly. Please read the post here: https://redd.it/flubzn

Thanks, 
Ross

**Comment by fosspill** [comment]
Thanks for the fix @rmountjoy92 ! And thanks for the fantastic tool.

**Comment by volcan96** [comment]
> Any idea how one would do this for docker? The current version in master is completely broken, so rolling back would be lovely. @fosspill 

For future reference see the high level steps in the comment about [switching commits](https://github.com/rmountjoy92/DashMachine/issues/41#issuecomment-601546431)
